var create_zone = function(zone){
    
    var height = 12;
    var width = 13; 
    var resultHTML = "";
//console.log('create zone start')
var Text_1 = '<!DOCTYPE html>\n<html lang="en"><head><meta charset="UTF-8">\n<title>Карта боевых действий зоны "' + zone.name + '"</title>\n   <link href="../../CSS/zona_main.css" rel="stylesheet">\n<link href="../../CSS/field.css" rel="stylesheet">\n<script type="text/javascript" src="../../JS/jquery-1.12.4.min.js"></script></head>';
    
var Text_2 = '<body><div id = "wrap"></div><div id = "info_panel"><div id = "info_panel_in"><div id="closePanel"></div><div id = "name_of_unit"></div><div id = "health_of_unit">Здоровье</div><div id = "value_health_of_unit">100%</div><div id = "tank_000_position"></div><div id = "tank_001_position"></div><div id = "tank_002_position"></div><div id = "tank_003_position"></div><div id = "tank_004_position"></div><div id = "tank_005_position"></div><div id = "tank_006_position"></div><div id = "tank_007_position"></div><div id = "tank_008_position"></div><div id = "tank_009_position"></div><div id = "GRAD_000_position"></div><div id = "GRAD_001_position"></div><div id = "GRAD_002_position"></div><div id = "GRAD_003_position"></div><div id = "ARTA_000_position"></div><div id = "ARTA_001_position"></div><div id = "ARTA_002_position"></div><div id = "infantery_000_position"></div><div id = "infantery_001_position"></div><div id = "infantery_002_position"></div><div id = "infantery_003_position"></div><div id = "infantery_004_position"></div><div id = "infantery_005_position"></div><div id = "infantery_006_position"></div><div id = "infantery_007_position"></div><div id = "infantery_008_position"></div><div id = "infantery_009_position"></div><div id = "mortan_000_position"></div><div id = "mortan_001_position"></div><div id = "mortan_002_position"></div><div id = "mortan_003_position"></div><div id = "mortan_004_position"></div><div id = "PTUR_000_position"></div><div id = "PTUR_001_position"></div><div id = "PTUR_002_position"></div><div id = "PTUR_003_position"></div><div id = "PTUR_004_position"></div><div id = "mortan2_000_position"></div><div id = "mortan2_001_position"></div><div id = "mortan2_002_position"></div><div id = "mortan2_003_position"></div><div id = "mortan2_004_position"></div><div id = "PTUR2_000_position"></div><div id = "PTUR2_001_position"></div><div id = "PTUR2_002_position"></div><div id = "PTUR2_003_position"></div><div id = "PTUR2_004_position"></div><div id = "infantery2_000_position"></div><div id = "infantery2_001_position"></div><div id = "infantery2_002_position"></div><div id = "infantery2_003_position"></div><div id = "infantery2_004_position"></div><div id = "infantery2_005_position"></div><div id = "infantery2_006_position"></div><div id = "infantery2_007_position"></div><div id = "infantery2_008_position"></div><div id = "infantery2_009_position"></div><div id = "BTR_000_position"></div><div id = "BTR_001_position"></div><div id = "BTR_002_position"></div><div id = "BTR_003_position"></div><div id = "BTR_004_position"></div></div></div>';
    
var Text_3 = '<div id = "main"><div id="big_map_zone"><img width="100%" ></div><div class = "circuit">';

 
var firstLine = height + 50;
var lastColumn = width + 10;

var Text_4=''
    for (var i =firstLine; i>=51; i=i-1){
        Text_4 = Text_4 + madeLine(i, lastColumn);
    }
    Text_4 = Text_4 + '</div>';
    
//var Text_5 = '<script type="text/javascript" src="../../JS/client/zone.js"\n var geoX = ' +zone.geoX+ '\n var geoY = '+ zone.geoY + '></script>'

var Text_5 ='<div id ="buttonNewCourse"><div id="our_down"><div id="our_save" onclick = ourSavePosition()></div><div id="our_save_off"></div><div id="our_load" onclick = ourLoadPosition()></div><div id="our_load_off"></div><div id ="our_step"></div><div id = "our_back_step" onclick = lastStep.backLastStep()></div><div id = "our_back_step_off"></div><div id = "our_trench" onclick = ourTrench()></div><div id = "our_trench_off"></div><div id = "our_mine" onclick = ourMine()></div><div id = "our_mine_off"></div><div id = "enemy_course" onclick = openEnemyCourse()></div><div class = "open_help_main" onclick = openHelpMain()></div></div><div id="enemy_down"><div id ="enemy_step"></div><div id ="enemy_step_1" onclick = enemyCourse1()></div><div id ="enemy_step_1_off" ></div><div id ="enemy_step_1_click" ></div><div id ="enemy_step_2" onclick = enemyCourse2()></div><div id ="enemy_step_2_off" ></div><div id ="enemy_step_2_click" ></div><div id ="enemy_step_3" onclick = enemyCourse3()></div><div id ="enemy_step_3_off" ></div><div id ="enemy_step_3_click" ></div><div class = "open_help_main" onclick = openHelpMain()></div></div></div></div>\n\n'

var Text_6_1 = '<div id = "battlefield"><div id = "wrap_field"></div><div id = "preload"></div><div class = "main"><div class = "left"><div id = "left_ARTA_GRAD"></div><div id = "left_trench"></div><div id = "left_PTUR"></div></div><div class = "center"><div class="upperLabel"><h2>ТАКТИЧЕСКАЯ КАРТА №<span id="number_of_tactic_map">001</span></h2></div><div class = "map" id = "map"><div id="small_map"> <img  width="155%" src="" ></div><table id = "battle_table"><tr><td id="0118" class="map_cell"></td><td id="0218" class="map_cell"></td><td id="0318" class="map_cell"></td><td id="0418" class="map_cell"></td><td id="0518" class="map_cell"></td><td id="0618" class="map_cell"></td><td id="0718" class="map_cell"></td><td id="0818" class="map_cell"></td><td id="0918" class="map_cell"></td><td id="1018" class="map_cell"></td><td id="1118" class="map_cell"></td><td id="1218" class="map_cell"></td><td id="1318" class="map_cell"></td><td id="1418" class="map_cell"></td><td id="1518" class="map_cell"></td><td id="1618" class="map_cell"></td><td id="1718" class="map_cell"></td><td id="1818" class="map_cell"></td></tr>'

var Text_6_2 = '<tr><td id="0117" class="map_cell"></td><td id="0217" class="map_cell"></td><td id="0317" class="map_cell"></td><td id="0417" class="map_cell"></td><td id="0517" class="map_cell"></td><td id="0617" class="map_cell"></td><td id="0717" class="map_cell"></td><td id="0817" class="map_cell"></td><td id="0917" class="map_cell"></td><td id="1017" class="map_cell"></td><td id="1117" class="map_cell"></td><td id="1217" class="map_cell"></td><td id="1317" class="map_cell"></td><td id="1417" class="map_cell"></td><td id="1517" class="map_cell"></td><td id="1617" class="map_cell"></td><td id="1717" class="map_cell"></td><td id="1817" class="map_cell"></td></tr><tr><td id="0116" class="map_cell"></td><td id="0216" class="map_cell"></td><td id="0316" class="map_cell"></td><td id="0416" class="map_cell"></td><td id="0516" class="map_cell"></td><td id="0616" class="map_cell"></td><td id="0716" class="map_cell"></td><td id="0816" class="map_cell"></td><td id="0916" class="map_cell"></td><td id="1016" class="map_cell"></td><td id="1116" class="map_cell"></td><td id="1216" class="map_cell"></td><td id="1316" class="map_cell"></td><td id="1416" class="map_cell"></td><td id="1516" class="map_cell"></td><td id="1616" class="map_cell"></td><td id="1716" class="map_cell"></td><td id="1816" class="map_cell"></td></tr><tr><td id="0115" class="map_cell"></td><td id="0215" class="map_cell"></td><td id="0315" class="map_cell"></td><td id="0415" class="map_cell"></td><td id="0515" class="map_cell"></td><td id="0615" class="map_cell"></td><td id="0715" class="map_cell"></td><td id="0815" class="map_cell"></td><td id="0915" class="map_cell"></td><td id="1015" class="map_cell"></td><td id="1115" class="map_cell"></td><td id="1215" class="map_cell"></td><td id="1315" class="map_cell"></td><td id="1415" class="map_cell"></td><td id="1515" class="map_cell"></td><td id="1615" class="map_cell"></td><td id="1715" class="map_cell"></td><td id="1815" class="map_cell"></td></tr>'

var Text_6_3 = '<tr><td id="0114" class="map_cell"></td><td id="0214" class="map_cell"></td><td id="0314" class="map_cell"></td><td id="0414" class="map_cell"></td><td id="0514" class="map_cell"></td><td id="0614" class="map_cell"></td><td id="0714" class="map_cell"></td><td id="0814" class="map_cell"></td><td id="0914" class="map_cell"></td><td id="1014" class="map_cell"></td><td id="1114" class="map_cell"></td><td id="1214" class="map_cell"></td><td id="1314" class="map_cell"></td><td id="1414" class="map_cell"></td><td id="1514" class="map_cell"></td><td id="1614" class="map_cell"></td><td id="1714" class="map_cell"></td><td id="1814" class="map_cell"></td></tr><tr><td id="0113" class="map_cell"></td><td id="0213" class="map_cell"></td><td id="0313" class="map_cell"></td><td id="0413" class="map_cell"></td><td id="0513" class="map_cell"></td><td id="0613" class="map_cell"></td><td id="0713" class="map_cell"></td><td id="0813" class="map_cell"></td><td id="0913" class="map_cell"></td><td id="1013" class="map_cell"></td><td id="1113" class="map_cell"></td><td id="1213" class="map_cell"></td><td id="1313" class="map_cell"></td><td id="1413" class="map_cell"></td><td id="1513" class="map_cell"></td><td id="1613" class="map_cell"></td><td id="1713" class="map_cell"></td><td id="1813" class="map_cell"></td></tr><tr><td id="0112" class="map_cell"></td><td id="0212" class="map_cell"></td><td id="0312" class="map_cell"></td><td id="0412" class="map_cell"></td><td id="0512" class="map_cell"></td><td id="0612" class="map_cell"></td><td id="0712" class="map_cell"></td><td id="0812" class="map_cell"></td><td id="0912" class="map_cell"></td><td id="1012" class="map_cell"></td><td id="1112" class="map_cell"></td><td id="1212" class="map_cell"></td><td id="1312" class="map_cell"></td><td id="1412" class="map_cell"></td><td id="1512" class="map_cell"></td><td id="1612" class="map_cell"></td><td id="1712" class="map_cell"></td><td id="1812" class="map_cell"></td></tr>'
    
var Text_6_4 = '<tr><td id="0111" class="map_cell"></td><td id="0211" class="map_cell"></td><td id="0311" class="map_cell"></td><td id="0411" class="map_cell"></td><td id="0511" class="map_cell"></td><td id="0611" class="map_cell"></td><td id="0711" class="map_cell"></td><td id="0811" class="map_cell"></td><td id="0911" class="map_cell"></td><td id="1011" class="map_cell"></td><td id="1111" class="map_cell"></td><td id="1211" class="map_cell"></td><td id="1311" class="map_cell"></td><td id="1411" class="map_cell"></td><td id="1511" class="map_cell"></td><td id="1611" class="map_cell"></td><td id="1711" class="map_cell"></td><td id="1811" class="map_cell"></td></tr><tr><td id="0110" class="map_cell"></td><td id="0210" class="map_cell"></td><td id="0310" class="map_cell"></td><td id="0410" class="map_cell"></td><td id="0510" class="map_cell"></td><td id="0610" class="map_cell"></td><td id="0710" class="map_cell"></td><td id="0810" class="map_cell"></td><td id="0910" class="map_cell"></td><td id="1010" class="map_cell"></td><td id="1110" class="map_cell"></td><td id="1210" class="map_cell"></td><td id="1310" class="map_cell"></td><td id="1410" class="map_cell"></td><td id="1510" class="map_cell"></td><td id="1610" class="map_cell"></td><td id="1710" class="map_cell"></td><td id="1810" class="map_cell"></td></tr><tr><td id="0109" class="map_cell"></td><td id="0209" class="map_cell"></td><td id="0309" class="map_cell"></td><td id="0409" class="map_cell"></td><td id="0509" class="map_cell"></td><td id="0609" class="map_cell"></td><td id="0709" class="map_cell"></td><td id="0809" class="map_cell"></td><td id="0909" class="map_cell"></td><td id="1009" class="map_cell"></td><td id="1109" class="map_cell"></td><td id="1209" class="map_cell"></td><td id="1309" class="map_cell"></td><td id="1409" class="map_cell"></td><td id="1509" class="map_cell"></td><td id="1609" class="map_cell"></td><td id="1709" class="map_cell"></td><td id="1809" class="map_cell"></td></tr>'
        
var Text_6_5 = '<tr><td id="0108" class="map_cell"></td><td id="0208" class="map_cell"></td><td id="0308" class="map_cell"></td><td id="0408" class="map_cell"></td><td id="0508" class="map_cell"></td><td id="0608" class="map_cell"></td><td id="0708" class="map_cell"></td><td id="0808" class="map_cell"></td><td id="0908" class="map_cell"></td><td id="1008" class="map_cell"></td><td id="1108" class="map_cell"></td><td id="1208" class="map_cell"></td><td id="1308" class="map_cell"></td><td id="1408" class="map_cell"></td><td id="1508" class="map_cell"></td><td id="1608" class="map_cell"></td><td id="1708" class="map_cell"></td><td id="1808" class="map_cell"></td></tr><tr><td id="0107" class="map_cell"></td><td id="0207" class="map_cell"></td><td id="0307" class="map_cell"></td><td id="0407" class="map_cell"></td><td id="0507" class="map_cell"></td><td id="0607" class="map_cell"></td><td id="0707" class="map_cell"></td><td id="0807" class="map_cell"></td><td id="0907" class="map_cell"></td><td id="1007" class="map_cell"></td><td id="1107" class="map_cell"></td><td id="1207" class="map_cell"></td><td id="1307" class="map_cell"></td><td id="1407" class="map_cell"></td><td id="1507" class="map_cell"></td><td id="1607" class="map_cell"></td><td id="1707" class="map_cell"></td><td id="1807" class="map_cell"></td></tr>'
    
var Text_6_6 = '<tr><td id="0106" class="map_cell"></td><td id="0206" class="map_cell"></td><td id="0306" class="map_cell"></td><td id="0406" class="map_cell"></td><td id="0506" class="map_cell"></td><td id="0606" class="map_cell"></td><td id="0706" class="map_cell"></td><td id="0806" class="map_cell"></td><td id="0906" class="map_cell"></td><td id="1006" class="map_cell"></td><td id="1106" class="map_cell"></td><td id="1206" class="map_cell"></td><td id="1306" class="map_cell"></td><td id="1406" class="map_cell"></td><td id="1506" class="map_cell"></td><td id="1606" class="map_cell"></td><td id="1706" class="map_cell"></td><td id="1806" class="map_cell"></td></tr><tr><td id="0105" class="map_cell"></td><td id="0205" class="map_cell"></td><td id="0305" class="map_cell"></td><td id="0405" class="map_cell"></td><td id="0505" class="map_cell"></td><td id="0605" class="map_cell"></td><td id="0705" class="map_cell"></td><td id="0805" class="map_cell"></td><td id="0905" class="map_cell"></td><td id="1005" class="map_cell"></td><td id="1105" class="map_cell"></td><td id="1205" class="map_cell"></td><td id="1305" class="map_cell"></td><td id="1405" class="map_cell"></td><td id="1505" class="map_cell"></td><td id="1605" class="map_cell"></td><td id="1705" class="map_cell"></td><td id="1805" class="map_cell"></td></tr><tr><td id="0104" class="map_cell"></td><td id="0204" class="map_cell"></td><td id="0304" class="map_cell"></td><td id="0404" class="map_cell"></td><td id="0504" class="map_cell"></td><td id="0604" class="map_cell"></td><td id="0704" class="map_cell"></td><td id="0804" class="map_cell"></td><td id="0904" class="map_cell"></td><td id="1004" class="map_cell"></td><td id="1104" class="map_cell"></td><td id="1204" class="map_cell"></td><td id="1304" class="map_cell"></td><td id="1404" class="map_cell"></td><td id="1504" class="map_cell"></td><td id="1604" class="map_cell"></td><td id="1704" class="map_cell"></td><td id="1804" class="map_cell"></td></tr>'
    
var Text_6_7 = '<tr><td id="0103" class="map_cell"></td><td id="0203" class="map_cell"></td><td id="0303" class="map_cell"></td><td id="0403" class="map_cell"></td><td id="0503" class="map_cell"></td><td id="0603" class="map_cell"></td><td id="0703" class="map_cell"></td><td id="0803" class="map_cell"></td><td id="0903" class="map_cell"></td><td id="1003" class="map_cell"></td><td id="1103" class="map_cell"></td><td id="1203" class="map_cell"></td><td id="1303" class="map_cell"></td><td id="1403" class="map_cell"></td><td id="1503" class="map_cell"></td><td id="1603" class="map_cell"></td><td id="1703" class="map_cell"></td><td id="1803" class="map_cell"></td></tr><tr><td id="0102" class="map_cell"></td><td id="0202" class="map_cell"></td><td id="0302" class="map_cell"></td><td id="0402" class="map_cell"></td><td id="0502" class="map_cell"></td><td id="0602" class="map_cell"></td><td id="0702" class="map_cell"></td><td id="0802" class="map_cell"></td><td id="0902" class="map_cell"></td><td id="1002" class="map_cell"></td><td id="1102" class="map_cell"></td><td id="1202" class="map_cell"></td><td id="1302" class="map_cell"></td><td id="1402" class="map_cell"></td><td id="1502" class="map_cell"></td><td id="1602" class="map_cell"></td><td id="1702" class="map_cell"></td><td id="1802" class="map_cell"></td></tr><tr><td id="0101" class="map_cell"></td><td id="0201" class="map_cell"></td><td id="0301" class="map_cell"></td><td id="0401" class="map_cell"></td><td id="0501" class="map_cell"></td><td id="0601" class="map_cell"></td><td id="0701" class="map_cell"></td><td id="0801" class="map_cell"></td><td id="0901" class="map_cell"></td><td id="1001" class="map_cell"></td><td id="1101" class="map_cell"></td><td id="1201" class="map_cell"></td><td id="1301" class="map_cell"></td><td id="1401" class="map_cell"></td><td id="1501" class="map_cell"></td><td id="1601" class="map_cell"></td><td id="1701" class="map_cell"></td><td id="1801" class="map_cell"></td></tr></table></div></div><div class = "down_bar"><div id = "auto_icon" onclick = autoBattleFunction()></div><div class = "open_help_main" onclick = openHelpMain2()></div></div><div class = "right"><div id = "right_ARTA_GRAD"></div><div id = "right_trench"></div><div id = "right_PTUR"></div></div></div></div>'


var endText = '<script >$("#big_map_zone img").attr("src", "https://static-maps.yandex.ru/1.x/?ll=" + (' + zone.geoX + ') + "," + ('+ zone.geoY + ') +"&z=12&l=map&\&size=500,410");</script><script type="text/javascript" src="../../JS/client/zone.js"></script>\n<script type="text/javascript" src="../../JS/client/zone_main.js"></script>\n<script type="text/javascript" src="../../JS/client/zone_field.js"></script>\n<script type="text/javascript" src="../../JS/client/zone_tactic.js"></script>\n<script type="text/javascript" src="../../JS/client/zone_auto.js"></script>\</body>\n</html>';
    
   resultHTML = Text_1 + Text_2 + Text_3 + Text_4 + Text_5 + Text_6_1 +Text_6_2 +Text_6_3 +Text_6_4 +Text_6_5 +Text_6_6 +Text_6_7 + endText;
    
    return resultHTML;
    
function madeLine(line, column){ // line - (линия 11хх)  column - (количество столбцов на карте xx12)
    var result = '';
    
    
    if (line%2 != 0){ // нечетная строка
        result = '<div class="line_2"> \n'
        for(var i=11; i<=column; i++){
            result = result + '<div id="' + line + i + '" class="cell line_2_cell">' + line + i + '</div>\n'
        }
        result = result +'</div>';
        return result;
    }
    if (line%2 == 0){ // четная строка
        result = '<div class="line_1"> \n'
        for(var i=11; i<=column; i++){
            result = result + '<div id="' + line + i + '" class="cell line_1_cell">' + line + i + '</div>\n'
        }
        result = result +'</div>';
        return result;
    }
} 
}

module.exports = create_zone;

